language: node_js
node_js:
  - "stable"
  install: yarn
  script: yarn test
  cache:
    directories:
      - "node_modules"
      - "test"

# safelist
branches:
  only:
    - develop
services:
    - postgresql
before_script:
    - psql -c "CREATE DATABASE"