language: node_js
node_js:
  - 'stable'
  install: npm install
  script: npm test
  cache:
    directories:
      - 'node_modules'

# safelist
branches:
  only:
    - develop
services:
    - postgresql
before_script:
    - psql -c 'create database teamwork;' -U postgres
after_success: npm coverage